# Generated by Django 5.0.6 on 2024-05-12 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOverlayIP',
            fields=[
                ('address', models.GenericIPAddressField(primary_key=True, protocol='ipv4', serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('key', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='base_tag_key_1f2c48_idx')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('config', models.JSONField()),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s_tags', to='base.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('committed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('committed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('committed', models.BooleanField(default=False)),
                ('base_config', models.JSONField()),
                ('config_changes', models.JSONField()),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s_tags', to='base.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
