# Generated by Django 5.0.6 on 2024-05-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOverlayIP',
            fields=[
                ('address', models.GenericIPAddressField(primary_key=True, protocol='ipv4', serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.BigIntegerField(db_index=True, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('key', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.BigIntegerField(db_index=True, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('committed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('committed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('committed', models.BooleanField(default=False)),
                ('changes', models.JSONField(default=dict)),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_snapshots', to='base.snapshotconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, default=dict, null=True)),
                ('object_id', models.BigIntegerField(editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['object_id'], name='base_tag_object__d024f1_idx'), models.Index(fields=['key', 'object_id'], name='base_tag_key_fd57b8_idx')],
                'unique_together': {('key', 'object_id')},
            },
        ),
    ]
