# Generated by Django 5.0.6 on 2024-05-21 08:07

import settings_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SASEInfraSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=255, validators=[settings_app.models.validate_cidr])),
                ('tags', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('sase_bgp_asn', models.PositiveIntegerField(default=64512, verbose_name='SASE BGP ASN')),
                ('sdwan_bgp_asn', models.PositiveIntegerField(default=64513, verbose_name='SD-WAN BGP ASN')),
                ('sase_community', models.CharField(default='64512:1', max_length=255, verbose_name='SASE Community')),
                ('sdwan_community', models.CharField(default='64513:1', max_length=255, verbose_name='SD-WAN Community')),
            ],
        ),
    ]
